my_portal/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.shortcuts import redirect
from django.template.defaulttags import url

from django.urls import path, include
from django.views.generic import TemplateView

from news import views
from news.views import subscribe_news, subscribe_articles
from protect.views import IndexView
from sign.views import upgrade_me, BaseRegisterView, CustomLogoutView, update_profile

from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from news.views import Index

app_name = 'sign'



# Добавил немного последовательности, ТАК ЧТОБ открыл новость ИСПРАВИЛ - не понравилось. УДАЛИЛ, С РАСЧЕТОМ, ЧТО Я ПРАВИЛЬНО ПОНЯЛ ТЗ
urlpatterns = [
    path('admin/', admin.site.urls),

    path('post/', views.PostsListView.as_view(), name='posts_list'),

    path('news/', views.NewsListView.as_view(), name='news_list'),

    path('confirm_email/', upgrade_me, name='protect'),

    path('news/<int:id>/', views.news_full_detail, name='news_full_detail'),

    path('articles/<int:id>/', views.articles_full_detail, name='articles_full_detail'),

    path('', include('sign.urls')),

    path('news/news_search/', views.PostsListView.as_view(), name='news_search'),

    path('news/create/', views.PostCreate.as_view(), name='create'),

    path('news/<int:pk>/edit/', views.PostUpdate.as_view()),

    path('edit/', views.PostUpdate.as_view()),

    path('', include('news.urls')),

    path('delete/', views.PostDelete.as_view(), name='delete'),

    path('<int:pk>/edit/', views.PostUpdate.as_view(), name='edit'),

    path('<int:pk>/delete/', views.PostUpdate.as_view(), name='delete'),


    path('accounts/login/protect/logout', LoginView.as_view(template_name='login.html', success_url='protect.html'),
            name='login'),

    path('login/',  LoginView.as_view(template_name='login.html', success_url='protect.html'),
            name='login'),

    path('login/', BaseRegisterView.as_view(template_name='signup.html'), name='signup'),

    path('login/protect/', include('news.urls')),

    path('login/protect/<int:pk>/edit', views.PostUpdate.as_view(), name='edit'),

    path('login/protect/<int:pk>/delete', views.PostUpdate.as_view(), name='delete'),

    path('login/protect/news/news_search',  views.PostsListView.as_view(), name='news_search'),

    ########path('sign/logout/', CustomLogoutView.as_view()),

    path('accounts/', include('allauth.urls')), #####

    path('accounts/signup/protect/', IndexView.as_view()),

    path('accounts/signup/protect/news/', IndexView.as_view()),

    path('accounts/login/protect/', IndexView.as_view()),

    path('accounts/signup/protect/sign/logout/', CustomLogoutView.as_view()),

    path('accounts/signup/protect/news/', views.NewsListView.as_view()),

    path('accounts/email/news/', views.NewsListView.as_view()),

    path('accounts/email/profile', update_profile, name='profile.html'),

    path('accounts/signin/protect/news/', views.NewsListView.as_view()),

    path('accounts/signin/protect/profile', update_profile, name='profile.html'),

    path('accounts/signup/protect/upgrade', upgrade_me, name='upgrade'),

    path('accounts/logout/logout/', IndexView.as_view()),

    path('accounts/signup/', BaseRegisterView.as_view(template_name='signup.html'), name='signup'),


    path('accounts/signup/protect/logout', CustomLogoutView.as_view()),
    # ВОТ ЗДЕЕСЬ
    path('upgrade/', upgrade_me, name='protect'),


    ###path('', CustomLogoutView.as_view(), name='logout'),
    # not work 405 conflict post, get: path('protect/logout/', LogoutView.as_view(template_name='sign/logout.html'),
         #name='logout'),


    path('signup/', BaseRegisterView.as_view(template_name='signup.html'), name='signup'),

    path('login/protect/logout/', CustomLogoutView.as_view()),

    path('upgrade/protect/', upgrade_me, name='protect'),

    path('accounts/signup/', BaseRegisterView.as_view(template_name='signup.html'), name='signup'), # Автоматичесое добавл. в группу commom


    path('profile/', update_profile, name='profile.html'),

    path('confirm_email/', upgrade_me, name='protect'),
    path('confirm_email/sign/login/', include('protect.urls')),
    path('confirm_email/sign/login/sign/login/',include('protect.urls')),


    path('subscribe/news/', subscribe_news, name='subscribe_news'),
    path('subscribe/articles/', subscribe_articles, name='subscribe_articles'),


    # path('login/protect/news/<int:id>/', views.protect_news, name='protect_news'),
    # path('login/protect/articles/<int:id>/', views.protect_articles, name='protect_articles'),

    path('q_news/', views.q_news, name='q_news.html'),



    path('i18n/', include('django.conf.urls.i18n')),
    path('Index/', views.Index.as_view(), name='index_msg'),

    path('swagger-ui/', TemplateView.as_view(
        template_name='swagger-ui.html',
        extra_context={'schema_url': '/static/openapi-schema.yml'}), name='swagger-ui'),


    path('authors/', views.AuthorViewSet.as_view({'get': 'list', 'post': 'create'}), name='author-list'),
    path('authors/<int:pk>/', views.AuthorViewSet.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}),
         name='author-detail'),

    path('posts/', views.PostViewSet.as_view({'get': 'list', 'post': 'create'}), name='post-list'),
    path('posts/<int:pk>/', views.PostViewSet.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}),
         name='post-detail'),

    path('comments/', views.CommentViewSet.as_view({'get': 'list', 'post': 'create'}), name='comment-list'),
    path('comments/<int:pk>/', views.CommentViewSet.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}),
         name='comment-detail'),

    path('categories/', views.CategoryViewSet.as_view({'get': 'list', 'post': 'create'}), name='category-list'),
    path('categories/<int:pk>/',
         views.CategoryViewSet.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}),
         name='category-detail'),



    ]

# urlpatterns += i18n_patterns(path('Index/', views.Index.as_view(), name='index_msg'),
#     path('', include('news.urls')), )



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

news/urls.py
from . import views
### from django.views.decorators.cache import cache_page
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    #####CASHES#### path('news/', cache_page(60)(views.NewsListView.as_view()), name='news_list'),
    path('news/', views.NewsListView.as_view(), name='news_list'),
    # path('', views.index, name='index'),
    path('<int:pk>/delete', views.PostDelete.as_view(), name='delete'),
    path('news/<int:id>/', views.news_full_detail, name='news_full_detail'),
    path('<int:id>/', views.news_full_detail, name='news_full_detail'),
    path('news_search/',  views.PostsListView.as_view(), name='news_search'),
    path('news/create/', views.PostCreate.as_view(), name='create'),
    path('news/<int:pk>/edit', views.PostUpdate.as_view(), name='edit'),
    path('news/<int:pk>/delete/', views.PostDelete.as_view(), name='delete'),




    #####CASHES#### path('articles/', cache_page(60)(views.ArticlesListView.as_view()), name='articles_list'),
    path('articles/', views.ArticlesListView.as_view(), name='articles_list'),

    path('articles/create/', views.PostCreate.as_view(), name='create'),

    path('articles/<int:id>/', views.articles_full_detail, name='articles_full_detail'),

    path('articles/<int:pk>/edit', views.PostUpdate.as_view(), name='edit'),

    path('articles/<int:pk>/delete/', views.PostDelete.as_view(), name='delete'),




]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

protect/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.IndexView.as_view()),
]

protect/models.py
from django.db import models

# Create your models here.

protect/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

class IndexView(LoginRequiredMixin, TemplateView):
    template_name = 'protect.html'

protect/templates/index.html
{% extends "main.html" %}

{% block content %}
<h2>Страница авторизованного пользователя {{ request.user.username }}</h2>
<div>Здесь может содержаться персональная информация для каждого пользователя</div>
{% if is_not_author %}
<a href="{% url 'upgrade' %}"><button>Хочу Premium!</button></a>
{% endif %}
<a href="{% url 'logout' %}"><button>Выйти</button></a>
{% endblock %}

protect/templates/logout.html
{% extends "main.html" %}

{% block content %}
<h2> Вы вышли из системы </h2>
{% endblock %}

protect/templates/main.html
<html>
    <head>
        <title> Simple SignUp/SignIn app</title>
    </head>
    <body>
        <div>
            <h1><a href="/">Simple SignUp/SignIn app</a></h1>
        </div>
        {% block content %}
        {% endblock %}
    </body>
</html>

protect/templates/news_list.html
{% extends 'flatpages/default.html' %}
{% load censor %}

{% block content %}

<h1><***News***></h1>
{% for post in posts %}
<a href="{% url 'news_full_detail' id=post.id %}" class="btn btn-warning">Подробнее
    <h2>{{ post.title|censor }}</h2>
</a>
<p><strong>Published:</strong> {{ post.created_at|date:"d.m.Y" }}</p>
<p>{{ post.content|slice:":21"|censor }}</p>
<p><strong>Автор:</strong> {{ post.authorname }}</p>
{% endfor %}

<form method="post" action="{% url 'news_list'  %}">
    {% csrf_token %}
    <button type="submit">Подписаться</button>
</form>

{# Добавляем пагинацию на страницу #}

{# Информация о предыдущих страницах #}
{% if page_obj.has_previous %}
<a href="?page=1">1</a>
{% if page_obj.previous_page_number != 1 %}
...
<a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
{% endif %}
{% endif %}

{# Информация о текущей странице #}
{{ page_obj.number }}

{# Информация о следующих страницах #}
{% if page_obj.has_next %}
<a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
{% if paginator.num_pages != page_obj.next_page_number %}
...
<a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
{% endif %}
{% endif %}

{% endblock content %}

protect/templates/protect.html
ing the URLs and displaying messages:

{% extends "main.html" %}

{% block content %}
<h2>Страница авторизованного пользователя {{ request.user.username }}</h2>
<div>Здесь может содержаться персональная информация для каждого пользователя</div>


<!--<button>
    <a href="protect"> Хочу Authors!</a>
</button>-->
{% if is_authors %}
<p>You are in the group.</p>
{% else %}
<form method="post" action="{% url 'sign:protect' %}">
    {% csrf_token %}
    <button type="submit">Хочу Authors!</button>
</form>
{% endif %}

<button>
    <a href="logout">Выйти</a>
</button>

<!-- Display messages -->
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li>{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
{% endblock %}