my_portal/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.shortcuts import redirect
from django.template.defaulttags import url

from django.urls import path, include
from django.views.generic import TemplateView

from news import views
from news.views import subscribe_news, subscribe_articles
from protect.views import IndexView
from sign.views import upgrade_me, BaseRegisterView, CustomLogoutView, update_profile

from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from news.views import Index

app_name = 'sign'



# Добавил немного последовательности, ТАК ЧТОБ открыл новость ИСПРАВИЛ - не понравилось. УДАЛИЛ, С РАСЧЕТОМ, ЧТО Я ПРАВИЛЬНО ПОНЯЛ ТЗ
urlpatterns = [
    path('admin/', admin.site.urls),

    path('post/', views.PostsListView.as_view(), name='posts_list'),

    path('news/', views.NewsListView.as_view(), name='news_list'),

    path('confirm_email/', upgrade_me, name='protect'),

    path('news/<int:id>/', views.news_full_detail, name='news_full_detail'),

    path('articles/<int:id>/', views.articles_full_detail, name='articles_full_detail'),

    path('', include('sign.urls')),

    path('news/news_search/', views.PostsListView.as_view(), name='news_search'),

    path('news/create/', views.PostCreate.as_view(), name='create'),

    path('news/<int:pk>/edit/', views.PostUpdate.as_view()),

    path('edit/', views.PostUpdate.as_view()),

    path('', include('news.urls')),

    path('delete/', views.PostDelete.as_view(), name='delete'),

    path('<int:pk>/edit/', views.PostUpdate.as_view(), name='edit'),

    path('<int:pk>/delete/', views.PostUpdate.as_view(), name='delete'),


    path('accounts/login/protect/logout', LoginView.as_view(template_name='login.html', success_url='protect.html'),
            name='login'),

    path('login/',  LoginView.as_view(template_name='login.html', success_url='protect.html'),
            name='login'),

    path('login/', BaseRegisterView.as_view(template_name='signup.html'), name='signup'),

    path('login/protect/', include('news.urls')),

    path('login/protect/<int:pk>/edit', views.PostUpdate.as_view(), name='edit'),

    path('login/protect/<int:pk>/delete', views.PostUpdate.as_view(), name='delete'),

    path('login/protect/news/news_search',  views.PostsListView.as_view(), name='news_search'),

    ########path('sign/logout/', CustomLogoutView.as_view()),

    path('accounts/', include('allauth.urls')), #####

    path('accounts/signup/protect/', IndexView.as_view()),

    path('accounts/signup/protect/news/', IndexView.as_view()),

    path('accounts/login/protect/', IndexView.as_view()),

    path('accounts/signup/protect/sign/logout/', CustomLogoutView.as_view()),

    path('accounts/signup/protect/news/', views.NewsListView.as_view()),

    path('accounts/email/news/', views.NewsListView.as_view()),

    path('accounts/email/profile', update_profile, name='profile.html'),

    path('accounts/signin/protect/news/', views.NewsListView.as_view()),

    path('accounts/signin/protect/profile', update_profile, name='profile.html'),

    path('accounts/signup/protect/upgrade', upgrade_me, name='upgrade'),

    path('accounts/logout/logout/', IndexView.as_view()),

    path('accounts/signup/', BaseRegisterView.as_view(template_name='signup.html'), name='signup'),


    path('accounts/signup/protect/logout', CustomLogoutView.as_view()),
    # ВОТ ЗДЕЕСЬ
    path('upgrade/', upgrade_me, name='protect'),


    ###path('', CustomLogoutView.as_view(), name='logout'),
    # not work 405 conflict post, get: path('protect/logout/', LogoutView.as_view(template_name='sign/logout.html'),
         #name='logout'),


    path('signup/', BaseRegisterView.as_view(template_name='signup.html'), name='signup'),

    path('login/protect/logout/', CustomLogoutView.as_view()),

    path('upgrade/protect/', upgrade_me, name='protect'),

    path('accounts/signup/', BaseRegisterView.as_view(template_name='signup.html'), name='signup'), # Автоматичесое добавл. в группу commom


    path('profile/', update_profile, name='profile.html'),

    path('confirm_email/', upgrade_me, name='protect'),
    path('confirm_email/sign/login/', include('protect.urls')),
    path('confirm_email/sign/login/sign/login/',include('protect.urls')),


    path('subscribe/news/', subscribe_news, name='subscribe_news'),
    path('subscribe/articles/', subscribe_articles, name='subscribe_articles'),


    # path('login/protect/news/<int:id>/', views.protect_news, name='protect_news'),
    # path('login/protect/articles/<int:id>/', views.protect_articles, name='protect_articles'),

    path('q_news/', views.q_news, name='q_news.html'),



    path('i18n/', include('django.conf.urls.i18n')),
    path('Index/', views.Index.as_view(), name='index_msg'),

    path('swagger-ui/', TemplateView.as_view(
        template_name='swagger-ui.html',
        extra_context={'schema_url': '/static/openapi-schema.yml'}), name='swagger-ui'),


    path('authors/', views.AuthorViewSet.as_view({'get': 'list', 'post': 'create'}), name='author-list'),
    path('authors/<int:pk>/', views.AuthorViewSet.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}),
         name='author-detail'),

    path('posts/', views.PostViewSet.as_view({'get': 'list', 'post': 'create'}), name='post-list'),
    path('posts/<int:pk>/', views.PostViewSet.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}),
         name='post-detail'),

    path('comments/', views.CommentViewSet.as_view({'get': 'list', 'post': 'create'}), name='comment-list'),
    path('comments/<int:pk>/', views.CommentViewSet.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}),
         name='comment-detail'),

    path('categories/', views.CategoryViewSet.as_view({'get': 'list', 'post': 'create'}), name='category-list'),
    path('categories/<int:pk>/',
         views.CategoryViewSet.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}),
         name='category-detail'),



    ]

# urlpatterns += i18n_patterns(path('Index/', views.Index.as_view(), name='index_msg'),
#     path('', include('news.urls')), )



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

news/urls.py
from . import views
### from django.views.decorators.cache import cache_page
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    #####CASHES#### path('news/', cache_page(60)(views.NewsListView.as_view()), name='news_list'),
    path('news/', views.NewsListView.as_view(), name='news_list'),
    # path('', views.index, name='index'),
    path('<int:pk>/delete', views.PostDelete.as_view(), name='delete'),
    path('news/<int:id>/', views.news_full_detail, name='news_full_detail'),
    path('<int:id>/', views.news_full_detail, name='news_full_detail'),
    path('news_search/',  views.PostsListView.as_view(), name='news_search'),
    path('news/create/', views.PostCreate.as_view(), name='create'),
    path('news/<int:pk>/edit', views.PostUpdate.as_view(), name='edit'),
    path('news/<int:pk>/delete/', views.PostDelete.as_view(), name='delete'),




    #####CASHES#### path('articles/', cache_page(60)(views.ArticlesListView.as_view()), name='articles_list'),
    path('articles/', views.ArticlesListView.as_view(), name='articles_list'),

    path('articles/create/', views.PostCreate.as_view(), name='create'),

    path('articles/<int:id>/', views.articles_full_detail, name='articles_full_detail'),

    path('articles/<int:pk>/edit', views.PostUpdate.as_view(), name='edit'),

    path('articles/<int:pk>/delete/', views.PostDelete.as_view(), name='delete'),




]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

protect/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.IndexView.as_view()),
]

news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.core.exceptions import ObjectDoesNotExist


class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    rating = models.IntegerField(default=0)


    def update_rating(self):
        post_rating = sum([post.rating * 3 for post in self.post_set.all()])
        comment_rating = sum([comment.rating for comment in Comment.objects.filter(author=self)])
        post_comment_rating = sum([comment.rating for comment in Comment.objects.filter(post__author=self)])

        self.rating = post_rating + comment_rating + post_comment_rating
        self.save()

    def __str__(self):
        return self.user.username

    
    def best_user(self):
        best_author = Author.objects.all().order_by('-rating').first()
        best_user = best_author.user
        return best_user.user, best_author.rating



class Category(models.Model):
    name = models.CharField(max_length=100)
    post_type = models.CharField(max_length=255, choices=[('news', 'News'), ('article', 'Article')])
    subscribers = models.ManyToManyField(User, related_name='subscribed_categories', blank=True)
    posts = models.ManyToManyField('Post', related_name='post_categories')

    def __str__(self):
        return self.name

    def subscribe_user(self, user):
        self.subscribers.add(user)

class Post(models.Model):
    author = models.ForeignKey('Author', on_delete=models.CASCADE)
    POST_TYPES = (
        ('article', 'Article'),
        ('news', 'News'),
    )

    post_type = models.CharField(max_length=10, choices=POST_TYPES)
    created_at = models.DateTimeField(auto_now_add=True)
    categories = models.ManyToManyField('Category', through='PostCategory')
    title = models.CharField(max_length=255)
    content = models.TextField()
    rating = models.IntegerField(default=0)
    authorname = models.CharField(max_length=255)
    category = models.ForeignKey('Category', on_delete=models.CASCADE, related_name='post_related')

    def last_news(self):
        last_news = Post.objects.filter(created_at__lt=self.created_at).order_by('-created_at').first()
        return last_news

    def __str__(self):
        return f"{{'title': '{self.title}', 'content': '{self.content}'}}"



    def get_absolute_url(self):
        if self.post_type  == 'news':
            return reverse('news_full_detail', args=[str(self.id)])
        else:
            return reverse('articles_full_detail', args=[str(self.id)])

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        return self.content[:124] + '... something important'

    def display_best_post(self):
        best_post = Post.objects.filter(categories__name='Category1').order_by('-rating').first()
        best_post_preview = best_post.preview()
        best_post_content = best_post.content[:50]
        print("Best Post:")
        print("Created at:", best_post.created_at)
        print("Author:", best_post.author.user.username)
        print("Rating:", best_post.rating)
        print("Title:", best_post.title)
        print("Preview:", best_post_preview)
        print("Сontent:", best_post_content)
        return best_post


class PostCategory(models.Model):
    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    category = models.ForeignKey('Category', on_delete=models.CASCADE)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    rating = models.IntegerField(default=0)


    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

protect/models.py
from django.db import models

# Create your models here.

protect/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

class IndexView(LoginRequiredMixin, TemplateView):
    template_name = 'protect.html'

my_portal/templates/articles_list.html
{% extends 'flatpages/default.html' %}
{% load censor %}

{% block content %}

<h1><***Articles***></h1>
{% for post in posts %}
<a href="{% url 'articles_full_detail' id=post.id %}" class="btn btn-warning">Подробнее
    <h2>{{ post.title|censor }}</h2>
</a>
<p><strong>Published:</strong> {{ post.created_at|date:"d.m.Y" }}</p>
<p>{{ post.content|slice:":21"|censor }}</p>
<p><strong>Автор:</strong> {{ post.author }}</p>
{% endfor %}

<form method="post" action="{% url 'subscribe_articles' %}">
    <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
    <button type="submit">Подписаться на Articles</button>
</form>

{# Добавляем пагинацию на страницу #}

{# Информация о предыдущих страницах #}
{% if page_obj.has_previous %}
<a href="?page=1">1</a>
{% if page_obj.previous_page_number != 1 %}
...
<a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
{% endif %}
{% endif %}

{# Информация о текущей странице #}
{{ page_obj.number }}

{# Информация о следующих страницах #}
{% if page_obj.has_next %}
<a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
{% if paginator.num_pages != page_obj.next_page_number %}
...
<a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
{% endif %}
{% endif %}

{% endblock content %}

my_portal/templates/create.html
{% extends 'flatpages/default.html' %}
{% load censor %}

<!-- ЭТО СГЕНЕРИРОВАЛА SHELL console -->
<!--<div>-->
<!--    <label for="id_title">Название:</label>-->

<!--<input type="text" name="title" value="news20" maxlength="255" required id="id_title">-->

<!--</div>-->

<!--  <div>-->
<!--    <label for="id_authorname">Автор:</label>-->

<!--<input type="text" name="authorname" maxlength="255" id="id_authorname">-->

<!--</div>-->


{% block title %} Create The Post {% endblock title %}

{% block content %}
<h4>Creation</h4>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

my_portal/templates/news_list.html
{% extends 'flatpages/default.html' %}
{% load censor %}

{% block content %}

<h1><***News***></h1>
{% for post in posts %}
<a href="{% url 'news_full_detail' id=post.id %}" class="btn btn-warning">Подробнее
    <h2>{{ post.title|censor }}</h2>
</a>
<p><strong>Published:</strong> {{ post.created_at|date:"d.m.Y" }}</p>
<p>{{ post.content|slice:":21"|censor }}</p>
<p><strong>Автор:</strong> {{ post.author }}</p>
{% endfor %}

<h1>Подписаться на News</h1>
<form method="post" action="{% url 'subscribe_news' %}">
    <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
    <button type="submit">Подписаться на News</button>
</form>

{# Добавляем пагинацию на страницу #}

{# Информация о предыдущих страницах #}
{% if page_obj.has_previous %}
<a href="?page=1">1</a>
{% if page_obj.previous_page_number != 1 %}
...
<a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
{% endif %}
{% endif %}

{# Информация о текущей странице #}
{{ page_obj.number }}

{# Информация о следующих страницах #}
{% if page_obj.has_next %}
<a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
{% if paginator.num_pages != page_obj.next_page_number %}
...
<a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
{% endif %}
{% endif %}

{% endblock content %}

my_portal/templates/protect.html
{% extends "index.html" %}

{% block content %}
<h2>Страница авторизованного пользователя {{request.user.username}}</h2>
<div> Здесь может содержаться персональная информация для каждого пользователя </div>

<button> <a href="sign/logout/">Выйти</a> </button>
{% endblock %}